### ISSUE TITLE
Is non-reuse deprecated?

### ISSUE THREAD

**Issue by IonicaBizau** [jillix/bind-tab#4]
We must use `reuse: true` every time because the miids are NOT loaded multiple times on same page.

This means that using non-reuse becomes deprecated... Reuse will be true as default, and non-configurable, I guess.

**Comment by gabipetrovay** [comment]
With [this commit](https://github.com/jillix/mono/commit/e828fc437d5ee8dd1bbd9e3e402c4fb9efb08374) `reuse` is practically moved inside Mono: an already loaded module will show its DOM when loaded again. I did not commit it in the `master` of Mono because I am afraid of side effects (i.e. same module appended several times in its parent module). In this case, the bind-tab module becomes even simpler.

**Comment by gabipetrovay** [comment]
BUT, reuse would still makes sense: `show`/`hide` vs. `html("")`/`appendChild(module.dom)`.

@IonicaBizau ?

**Comment by IonicaBizau** [comment]
Hmm... If it works then it's fine. We can close this issue then.

**Comment by gabipetrovay** [comment]
[Here](http://salongenf.dev.jillix.net/) you have a live version using `reuse: false`
